# Generated by Django 4.0.4 on 2022-04-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourApp', '0002_remove_admin_profile_pic_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_by',
            new_name='author',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
